import { useState } from 'react'
import { Button, Card, ErrorMessage, Input, Modal, SeverityBadge, Table } from '../../components/common'
import { Header } from '../../components/layout'
import type { TableColumn } from '../../types'

type Rule = { id: string; name: string; pattern: string; severity: 'critical' | 'high' | 'medium' | 'low'; enabled: boolean }
const initialRules: Rule[] = [{ id: 'rule-auth-failure', name: 'Repeated authentication failures', pattern: 'AUTH_FAILURE|failed login', severity: 'high', enabled: true }]

const Settings = () => {
  const [preferences, setPreferences] = useState({ theme: 'system', language: 'English', emailAlerts: true, browserAlerts: true })
  const [rules, setRules] = useState(initialRules)
  const [thresholds, setThresholds] = useState({ critical: '1', high: '5', medium: '20' })
  const [api, setApi] = useState({ baseUrl: import.meta.env.VITE_API_URL || 'http://localhost:8000', mockApi: import.meta.env.VITE_USE_MOCK_API === 'true' })
  const [retentionDays, setRetentionDays] = useState('90')
  const [message, setMessage] = useState<string | null>(null)
  const [isRuleModalOpen, setRuleModalOpen] = useState(false)
  const [isClearModalOpen, setClearModalOpen] = useState(false)
  const [ruleForm, setRuleForm] = useState({ name: '', pattern: '', severity: 'medium' as Rule['severity'] })

  const savePreferences = () => { localStorage.setItem('log-analyzer-preferences', JSON.stringify(preferences)); document.documentElement.dataset.theme = preferences.theme; setMessage('User preferences saved.') }
  const saveAlerts = () => { localStorage.setItem('log-analyzer-alert-thresholds', JSON.stringify(thresholds)); setMessage('Alert thresholds saved.') }
  const saveApi = () => { localStorage.setItem('log-analyzer-api-configuration', JSON.stringify(api)); setMessage('API configuration saved for the next application session.') }
  const saveRetention = () => { localStorage.setItem('log-analyzer-retention-days', retentionDays); setMessage(`Log retention period set to ${retentionDays} days.`) }
  const addRule = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); try { new RegExp(ruleForm.pattern, 'i') } catch { setMessage('Enter a valid regular expression before saving the rule.'); return } if (!ruleForm.name.trim()) { setMessage('Enter a name for the analysis rule.'); return } setRules((currentRules) => [...currentRules, { id: crypto.randomUUID(), name: ruleForm.name.trim(), pattern: ruleForm.pattern, severity: ruleForm.severity, enabled: true }]); setRuleForm({ name: '', pattern: '', severity: 'medium' }); setRuleModalOpen(false); setMessage('Custom analysis rule saved.') }
  const clearLocalData = () => { ['log-analyzer-preferences', 'log-analyzer-alert-thresholds', 'log-analyzer-api-configuration', 'log-analyzer-retention-days'].forEach((key) => localStorage.removeItem(key)); setClearModalOpen(false); setMessage('Saved local settings and cached configuration were cleared.') }
  const ruleColumns: TableColumn[] = [{ key: 'name', label: 'Rule', sortable: true }, { key: 'pattern', label: 'Pattern', sortable: true }, { key: 'severity', label: 'Severity', sortable: true, render: (value: string) => <SeverityBadge severity={value} /> }, { key: 'enabled', label: 'Status', sortable: true, render: (value: boolean, rule: Rule) => <button type="button" onClick={(event) => { event.stopPropagation(); setRules((currentRules) => currentRules.map((currentRule) => currentRule.id === rule.id ? { ...currentRule, enabled: !currentRule.enabled } : currentRule)) }} className={`rounded-full px-3 py-1 text-xs font-medium ${value ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>{value ? 'Enabled' : 'Disabled'}</button> }]

  return <div className="p-6"><Header title="Settings & configuration" subtitle="Manage preferences, analysis rules, alerts, and local data" />
    {message && <ErrorMessage type="info" className="mb-6" message={message} onDismiss={() => setMessage(null)} />}
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
      <Card title="User preferences" subtitle="Personalize the application experience"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Select id="theme" label="Theme" value={preferences.theme} onChange={(value) => setPreferences({ ...preferences, theme: value })} options={['system', 'light', 'dark']} /><Select id="language" label="Language" value={preferences.language} onChange={(value) => setPreferences({ ...preferences, language: value })} options={['English', 'Hindi']} /></div><Toggle label="Email notifications" checked={preferences.emailAlerts} onChange={(value) => setPreferences({ ...preferences, emailAlerts: value })} /><Toggle label="Browser notifications" checked={preferences.browserAlerts} onChange={(value) => setPreferences({ ...preferences, browserAlerts: value })} /><div className="mt-5 flex justify-end"><Button onClick={savePreferences}>Save preferences</Button></div></Card>
      <Card title="Alert thresholds" subtitle="Choose how many matching events create an alert"><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Input type="number" min="1" label="Critical" value={thresholds.critical} onChange={(event) => setThresholds({ ...thresholds, critical: event.target.value })} /><Input type="number" min="1" label="High" value={thresholds.high} onChange={(event) => setThresholds({ ...thresholds, high: event.target.value })} /><Input type="number" min="1" label="Medium" value={thresholds.medium} onChange={(event) => setThresholds({ ...thresholds, medium: event.target.value })} /></div><div className="mt-5 flex justify-end"><Button onClick={saveAlerts}>Save thresholds</Button></div></Card>
      <Card className="xl:col-span-2" title="Analysis rules" subtitle="Create custom regular-expression rules to detect relevant log activity" actions={<Button variant="ghost" size="sm" onClick={() => setRuleModalOpen(true)}>Add rule</Button>}><Table data={rules} columns={ruleColumns} sortable emptyMessage="No analysis rules configured." /></Card>
      <Card title="API configuration" subtitle="Use the backend endpoint when it is available"><Input label="Backend API URL" value={api.baseUrl} onChange={(event) => setApi({ ...api, baseUrl: event.target.value })} helperText="Changes apply after the application is restarted." /><Toggle label="Use mock API data" checked={api.mockApi} onChange={(value) => setApi({ ...api, mockApi: value })} /><div className="mt-5 flex justify-end"><Button onClick={saveApi}>Save API configuration</Button></div></Card>
      <Card title="Data management" subtitle="Control browser-side settings and log retention"><Input type="number" min="1" label="Keep logs for (days)" value={retentionDays} onChange={(event) => setRetentionDays(event.target.value)} helperText="The backend retention job will use this setting when connected." /><div className="mt-5 flex flex-wrap justify-end gap-3"><Button variant="secondary" onClick={saveRetention}>Save retention</Button><Button variant="danger" onClick={() => setClearModalOpen(true)}>Clear local data</Button></div></Card>
    </div>
    <Modal isOpen={isRuleModalOpen} onClose={() => setRuleModalOpen(false)} title="Add analysis rule"><form onSubmit={addRule}><Input label="Rule name" value={ruleForm.name} onChange={(event) => setRuleForm({ ...ruleForm, name: event.target.value })} placeholder="e.g. Suspicious PowerShell execution" /><Input label="Regular expression" value={ruleForm.pattern} onChange={(event) => setRuleForm({ ...ruleForm, pattern: event.target.value })} placeholder="powershell|encodedcommand" helperText="The expression is checked before the rule is saved." /><Select id="rule-severity" label="Severity" value={ruleForm.severity} onChange={(value) => setRuleForm({ ...ruleForm, severity: value as Rule['severity'] })} options={['critical', 'high', 'medium', 'low']} /><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setRuleModalOpen(false)}>Cancel</Button><Button type="submit">Save rule</Button></div></form></Modal>
    <Modal isOpen={isClearModalOpen} onClose={() => setClearModalOpen(false)} title="Clear local data"><p className="text-sm text-gray-600">This removes saved preferences, thresholds, API configuration, and retention settings from this browser. It does not delete backend log records.</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={() => setClearModalOpen(false)}>Cancel</Button><Button variant="danger" onClick={clearLocalData}>Clear data</Button></div></Modal>
  </div>
}

const Select = ({ id, label, value, onChange, options }: { id: string; label: string; value: string; onChange: (value: string) => void; options: string[] }) => <div><label className="mb-1 block text-sm font-medium text-gray-700" htmlFor={id}>{label}</label><select id={id} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-gray-300 bg-white px-3 py-2 shadow-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500">{options.map((option) => <option key={option} value={option}>{option[0].toUpperCase() + option.slice(1)}</option>)}</select></div>
const Toggle = ({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) => <label className="mt-4 flex cursor-pointer items-center justify-between gap-3 rounded-md bg-gray-50 p-3"><span className="text-sm font-medium text-gray-700">{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500" /></label>

export default Settings
